### PR TITLE
Added new function `compact_table()`

### PR DESCRIPTION
**Pull request by ddsjoberg**
* Added new function `compact_table()` that makes the compact styling available in `gtsummary::theme_gtsummary_compact()` to any {gt}, {flextable}, {huxtable}, or `knitr::kable()` table.

```r
head(trial) %>%
  gt::gt() %>%
  compact_table()
```
image

### CODE REVIEW

**Review by jalavery — APPROVED** [review]
I love this function! Could there potentially be additional functions that style tables in the future? If so, may want to name this  `style_compact` or something so that the same prefix (`style_xx`) could be used for other formatting functions. Otherwise I had no comments - it works and the documentation is clear!

**Comment by ddsjoberg** [comment]
@jalavery thank you for reviewing!

I like the style prefix. I had originally wanted to stay away from it, because the other style functions in gtsummary only style vectors, but in the end I think it's a better name . I'll update it!

**Comment by ddsjoberg** [comment]
@jalavery what do you think of `style_tbl_compact()`?  Would leave us open to other functions that could style tables, `style_tbl_xxxx()`.

**Comment by jalavery** [comment]
Great - I like `style_tbl_compact`!

**Pull request merged**
