### PR TITLE
Likert

### LINKED ISSUE #53: Feature request: a tbl_likert ?
Opening this issue just to open a discussion on how to display Likert scales items with `gtsummary` and to see if it would be relevant (or not) to propose something.

Many social surveys includes attitudes/opinions questions using a Likert scales. The format of a typical five-level Likert item, for example, could be:

1. Strongly disagree
2. Disagree
3. Neither agree nor disagree
4. Agree
5. Strongly agree

In such a case, we have a set of categorical variables sharing the same set of levels. (sometimes, some work could be required to ensure that all levels are defined in all factors).

Displaying them with `tbl_summary()` will result in a long one-column table with the items repeated several times.

Another option could be to apply `tbl_summary()` on each variable and then to merge all sub-tables with `tbl_merge()` (or using `tbl_strata()`).

However, if we have a lot of items, it could be better to display factor levels in separate columns and variables in different rows. 
But I do not think that we currently have the equivalent of a `tbl_transpose()` in `gtsummary`.

Would/Should it be relevant to think about a dedicated `tbl_likert()` function or would it too specific?
If such a function is added, would it be relevant to also propose a `plot()` method?

### PR DESCRIPTION
**Pull request by ddsjoberg**
closes #53 

- [x] Implement `add_n()` method.
- [x] Use `forcats::fct_unify()`
- [x] Add tbl sorting

### CODE REVIEW

**Comment by larmarange** [comment]
Thanks @ddsjoberg for the proposal.

Some thoughts about potential functionalities for discussion.

- If all factors do not have the same levels, instead of a stop, we could harmonize the level with `forcats::fct_unify()` and display a message.

- We could add some methods `add_n()` and `add_missing()` to display the number of observations and missing observations.

- A method `add_score()` to present some summary statistic by considering the variables as continuous. By default, I would suggest to display `statistic = "{mean} ({sd})"`. In addition, it would be important to have an argument `score_values` to indicate how to transform the factor into a score. If `NULL`, simply use `as.integer(data[[variable]])`. If provided (e.g. `-2:2` for a five levels scales), using `score_values[as.integer(data[[variable]])]`.

**Comment by larmarange** [comment]
`add_overall()` for displaying a total 100% column?

**Comment by larmarange** [comment]
Would it be difficult to have an option or a method to order the table based on mean score?

**Comment by ddsjoberg** [comment]
> Should we fix missing = "no" when calling tbl_summary() and display the number of missing through a method add_missing() ?

We could add it, but the "variable" being summarized in `"...all_true..."`, which has no missing values. The missing values are auto-dropped because it's the `by=` variable. 

> Would it be difficult to have an option or a method to order the table based on mean score?

That shouldn't be too bad!

> add_overall() for displaying a total 100% column?

I am not sure I know what you have in mind here.

> A method add_score() to present some summary statistic by considering the variables as continuous.

This can be added. But perhaps not a priority, as a user can easily create the continuous summary then merge it with the likert table.

> Can we also think about a group option (for example group = "sex") to compute the likert table by sub-group and then to stack them?

This wouldn't be difficult to implement with `tbl_strata()`. I would imagine users would want to control whether the tbls are stacked or merged. It can be added, but i'll prioritize the other items first....need to think about best implementation.

**Pull request merged**
