### PR TITLE
added tbl_checkbox

### LINKED ISSUE #79: Feature request: Support for checkbox questions
I'm frequently using data sets that have 'checkbox' style questions in which the respondent selects any number of some set of discrete options. The resulting data is then spread across multiple columns, one for each option, and will just have a `1` or `NA` for possible values.

The function `gtsummary::tbl_summary` treats these each as their own variable instead of listing a common heading for them. Here is [my question from stackoverflow](https://stackoverflow.com/questions/70687858/formatting-gtsummary-tables-with-checkbox-questions/70688248#70688248) along with @ddsjoberg 's solution. This solution is okay but it's a bit tedious, especially if you have a lot of other variables in the data set.

Ideally, `gtsummary::tbl_summary` could be given a list of columns to treat as one question or a pattern to find them, and then apply this similar formatting.

Thank you! Love the library

### PR DESCRIPTION
**Pull request by ddsjoberg**
Adds new function `tbl_checkbox()`

closes #79

```r
set.seed(11234)
tbl_checkbox_ex1 <-
  data.frame(
    race_asian = sample(c(TRUE, FALSE), 20, replace = TRUE),
    race_black = sample(c(TRUE, FALSE), 20, replace = TRUE),
    race_white = sample(c(TRUE, FALSE), 20, replace = TRUE),
    age = rnorm(20, mean = 50, sd = 10)
  ) %>%
  tbl_checkbox(
    include =
      list("Race (check all that apply)" = c("race_asian", "race_black", "race_white"),
           "age"),
    label = list(race_asian = "Asian",
                 race_black = "Black",
                 race_white = "White",
                 age = "Age")
  )
```

image

### CODE REVIEW

**Comment by svenhalvorson** [comment]
Hi @ddsjoberg!

Thank you for putting some work into this! I'm not that familiar with pull requests but by hook and crook, I downloaded it and played around a bit. Here are my notes:

1. Works with both logical and binary numeric variables.
2. Nice that this does *not* require stacking tables.
3. Method of counting percents with missing values seems good
4. It seems a little tedious that we have to manually specify all the variables to `include`. Can we not just specify the grouped variables? 
5. Fails in the case that one of the grouped variables has only missing values. Can be fixed by specifying it is a dichotomous variable with the `type` argument
6. Doesn't seem to work if the variable has value labels (`expss::val_lab`). Maybe can just produce a warning? Issue is in `tbl_summary`

Overall this looks very good!

**Comment by ddsjoberg** [comment]
Thank you for doing the checks! @svenhalvorson MUCH APPRECITED! 

> 1. Works with both logical and binary numeric variables.

It should work with any variable that is type dichotomous.

> 2. Nice that this does _not_ require stacking tables.

Yes, I think this is the best part! 

> 4. It seems a little tedious that we have to manually specify all the variables to `include`. Can we not just specify the grouped variables?

I don't disagree, but I think would be tricky to get it to work otherwise 🤷🏼‍♂️ I am open to better implementations via pull requests from any users, but I will likely will not work on this in the future.

> 5. Fails in the case that one of the grouped variables has only missing values. Can be fixed by specifying it is a dichotomous variable with the `type` argument

Oh yes, that makes sense. But the message indicates it must be dichotomous, so hopefully that is helpful to the user.

> 6. Doesn't seem to work if the variable has value labels (`expss::val_lab`). Maybe can just produce a warning? Issue is in `tbl_summary`

Do these work in `tbl_summary()` but not here?





I think i will go ahead and merge this for now! thank you!

**Comment by ddsjoberg** [comment]
@svenhalvorson thinking about this more....

Perhaps a better solution is something like this:

```r
tbl_summary(...) %>%
  indent_grouped_variables("Race" = c("race_asian", "race_white", "race_black"))
```

Then you can use `tbl_summary()` as you already do, and define the groups after (which is essentially how the current version function works regardless).

I think I prefer this approach. Will need to think on it longer, and come up with a better name.

**Comment by svenhalvorson** [comment]
@ddsjoberg that sounds preferable solution. The function seems like it has more in common with something like `gtsummary::bold_labels` in that it modifies an existing table, not creating it.

Also, here is an example of `tbl_summary` not working with value labels:

```
tibble::tibble(
  labelled_var1 = expss::set_val_lab(1, c('a' = 1))
) %>% 
  gtsummary::tbl_summary(
    type = list(
      labelled_var1 ~ 'dichotomous'
    )
  )
```

**Comment by ddsjoberg** [comment]
@svenhalvorson hello hello hello!

Function updated! Can you please take a second look? This is already much better after your first round of feedback 💯 

```r
set.seed(11234)
add_variable_grouping_ex1 <-
  data.frame(
    race_asian = sample(c(TRUE, FALSE), 20, replace = TRUE),
    race_black = sample(c(TRUE, FALSE), 20, replace = TRUE),
    race_white = sample(c(TRUE, FALSE), 20, replace = TRUE),
    age = rnorm(20, mean = 50, sd = 10)
  ) %>%
  gtsummary::tbl_summary(
    label = list(race_asian = "Asian",
                 race_black = "Black",
                 race_white = "White",
                 age = "Age")
  ) %>%
  add_variable_grouping(
    "Race (check all that apply)" = c("race_asian", "race_black", "race_white")
  )
```
image

**Comment by svenhalvorson** [comment]
Hey @ddsjoberg !

I been away and forgot about this but I very much appreciate the addition.

I went ahead and tested this with my own application and it works very well. This is much closer to what I originally envisioned in that `add_variable_grouping` can be applied after `tbl_summary`.

The only thing I noticed that was suboptimal (but still workable) is that `add_bold_labels` bolds each row in the grouped variables, not just header.

**Comment by ddsjoberg** [comment]
Yes, the bolding using the bold_labels() function won't be great here.

There are two good options.
1. Use modify_table_styling() to apply bold precisely where you would like.
2. Convert the gtsummary table to gt (or another format) and use that package's styling functions to bold whatever cells you'd like

**Pull request merged**
