### PR TITLE
Adding `add_inline_forest_plot()`

### LINKED ISSUE #27: inline forest plot with `tbl_regression()`
It seems possible to mix `kableExtra` features with `gt` and therefore to include inline forest plots. cf. exemple here: https://themockup.blog/posts/2020-10-31-embedding-custom-features-in-gt-tables/#forest

Maybe it's a feature to keep in mind and that could be added one day in `gtsummary`

### PR DESCRIPTION
**Pull request by ddsjoberg**
* Adding function `add_inline_forest_plot()` (#27)

closes #27

```r
library(gtsummary)

add_inline_forest_plot_ex1 <-
  lm(mpg ~ cyl + am + drat, mtcars) %>%
  tbl_regression() %>%
  add_inline_forest_plot()
```
image

### CODE REVIEW

**Comment by ddsjoberg** [comment]
@larmarange do you want to take a look at this function? Should we add anything more?

Thanks for the suggestion...it looks so cute!

**Comment by larmarange** [comment]
I love it. That's really great and visual!!!!!

Just need few options to customize the column title and position. But really great. :-)

**Comment by larmarange** [comment]
Oh just a quick comment, if `exponentiate = TRUE`, you should plot the log values of the exponentiate (because the forest plot does  not accept a log scale)

**Comment by ddsjoberg** [comment]
great @larmarange !

1. I am not sure I can plot on the log scale. But I can certainly take the log of the estimates if they've been exponentiated. Since there are no axis numbers, the users won't know.  I'll add a note to the help file that exponentiated estimates are shown on the log scale.
2. I'll add a few other args!

**Pull request merged**
